version: '3.8'

services:
  web:
    build: .
    image: bwapp-php7:20240402
    container_name: bwapp
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
    networks:
      - webnet

  db:
    image: mysql:5.7
    container_name: bwapp_db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  nginx:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: nginx_modsecurity
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - webnet


volumes:
  db_data:

networks:
  webnet:
    driver: bridge
