version: '3.8'

services:
  web:
    image: raesene/bwapp:latest
    container_name: bwapp
    environment:
      - MYSQL_ROOT_PASSWORD=bee
      - MYSQL_USER=bee
      - MYSQL_PASSWORD=bee
    depends_on:
      - db
    networks:
      - webnet
    ports:
      - "4280:80"
    restart: unless-stopped

  db:
    image: mariadb:10
    container_name: bwapp-db
    environment:
      - MYSQL_ROOT_PASSWORD=bee
      - MYSQL_DATABASE=bWAPP_BAK
      - MYSQL_USER=alice
      - MYSQL_PASSWORD=loveZombies
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet
    restart: unless-stopped

  nginx:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: nginx_modsecurity
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - webnet


volumes:
  db_data:

networks:
  webnet:
    driver: bridge
