services:
  app:
    image: traefik/whoami
    restart: always
    networks:
      - backend
    
  reverse-proxy:
    image: nginx:alpine
    restart: always
    networks:
      - backend
    ports:
      - 80:80
    depends_on:
      - 'app'
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - crowdsec.enable=true
      - crowdsec.labels.type=nginx
    ## https://docs.crowdsec.net/docs/next/data_sources/docker#use_container_labels

networks:
  backend:
    driver: bridge
