version: '3.8'

services:
  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    restart: always
    ports:
      - "8080:80"
    networks:
      - bwapp_net

  nginx:
    image: nginx:latest
    container_name: nginx_bwapp
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bwapp
    networks:
      - bwapp_net

networks:
  bwapp_net:
    driver: bridge
