version: '3'

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest-debian
    restart: always
    environment:
    # DISABLE_PARSERS: "crowdsecurity/whitelists"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/iptables"
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /var/log/journal:/var/log/host:ro
      - crowdsec-db:/var/lib/crowdsec/data/
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      crowdsec:

volumes:
  crowdsec-db:

networks:
  crowdsec:
    driver: bridge
